{% set name = "Flask-RESTful" %}
{% set version = "0.3.8" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "5ea9a5991abf2cb69b4aac19793faac6c032300505b325687d7c305ffaa76915" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: {{ build }}
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - aniso8601 >=0.82
    - flask >=0.8
    - six >=1.3.0
    - pytz

test:
  imports:
    - flask_restful
    - flask_restful.representations
    - flask_restful.utils

about:
  home: https://www.github.com/flask-restful/flask-restful/
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'Simple framework for creating REST APIs'
  doc_url: https://flask-restful.readthedocs.io/en/latest/
  dev_url: https://www.github.com/flask-restful/flask-restful/

extra:
  recipe-maintainers:
    - pmlandwehr
